image_resizer:
  context:
    # student:
    #   table: hello
    # course:
    #   table: hello
    # classes:
    #   table: hello
    student:
      resized_image:
        width: 200
        height: 200
        quality: "100"
        resize_by: maxHeight
        location: "uploads/images/students"
      thumbnail:
        width: 50
        height: 50
        quality: "100"
        resize_by: maxHeight
        location: "uploads/images/students"
    course:
      resized_image:
        width: 400
        height: 400
        quality: "100"
        resize_by: maxHeight
        location: "uploads/images/courses"
      thumbnail:
        width: 50
        height: 50
        quality: "100"
        resize_by: maxHeight
        location: "uploads/images/courses"
    classes:
      resized_image:
        width: 75
        height: 75
        quality: "100"
        resize_by: maxHeight
        location: "uploads/images/classes"
      thumbnail:
        width: 50
        height: 50
        quality: "100"
        resize_by: maxHeight
        location: "uploads/images/classes"
# default:
#   resized_image:
#     width: 200
#     height: 200
#     quality: "100"
#     resize_by: maxHeight
#     location: "uploads/images/classes"
#   thumbnail:
#     width: 50
#     height: 50
#     quality: "100"
#     resize_by: maxHeight
#     location: "uploads/images/classes"
