#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# all_courses:
#   path: /api/v1/courses
#   controller: App\Controller\CourseApiController::listClasses
#   methods: ["GET"]
# new_courses:
#   path: /api/v1/courses
#   controller: App\Controller\CourseApiController::listClasses
#   methods: ["GET"]

api_login_check:
  path: /api/login
